### ISSUE TITLE
add package.json

### ISSUE THREAD

**Issue by gekkedev** [anonyco/BestBase64EncoderDecoder#2]
Would it be possible to make this repository accessible as npm package?

**Comment by anonyco** [comment]
Thank you for bringing this to my attention. I believe that I have published the package at [https://www.npmjs.com/package/bestbase64utf8](https://www.npmjs.com/package/bestbase64utf8).

However, this is my first package, so it is certainly possible that I made a mistake. So, if it is not too much trouble, may I please ask you to take a quick glance at this published project to make sure that I did not botch it up somehow? It would mean a lot me and especially to my dignity :+1:

**Comment by bram-ontoforce** [comment]
I had some trouble using this package from npm because the source code is written in es6 (and by default I ignore the node_modules folder with babel for performance reasons), see also [here](https://stackoverflow.com/questions/29738381/how-to-publish-a-module-written-in-es6-to-npm).

It would be very nice if you can publish it in plain javascript, but thanks for sharing the code anyway!

**Comment by gekkedev** [comment]
@anonyco I have tested the package, it looks alright for now. I've left you a pull request (#4) for minor improvements though. Closing this issue now as it is solved.

> It would be very nice if you can publish it in plain javascript, but thanks for sharing the code anyway!

@bram-ontoforce  I'm afraid ES6 is pure and plain Javascript, it just might be too new to some outdated (and therefore unsafe) browsers. If you feel like polyfills aren't your thing you may open a separate issue to start a discussion on that.

**Comment by anonyco** [comment]
@bram-ontoforce

I am very interested in what you have to say. I checked you link, but I still do not entirely understand what you are asking. Could you please clarify what you want me to do.
